mysql:
    host: localhost
    user: root
    passwd: my secret password
    db: write-math
    best-jedi: {name: Obi-Wan, side: light} 

other:
    preprocessing_queue:
        - preprocessing.scale_and_center
        - preprocessing.dot_reduction
        - preprocessing.connect_lines
    use_anonymous: yes